#!/bin/bash

ALL_VERSIONS= 
INDEX=1

ALL_VERSIONS=$(echo `curl -s https://api.github.com/repos/krb5/krb5/tags | grep name | cut -d '"' -f 4 | cut -d "-" -f 2`)

echo ALL_VERSIONS=$ALL_VERSIONS

VERSION=$(echo $ALL_VERSIONS |  cut -d " " -f $INDEX)
let "INDEX++"

echo VERSION=$VERSION

while ! [[ $VERSION =~ [0-9] ]]
do
  VERSION=$(echo $ALL_VERSIONS |  cut -d " " -f $INDEX)
  echo VERSION=$VERSION
  let "INDEX++"
done


MAJOR_VERSION=$(echo $VERSION | cut -d '.' -f1)
MINOR_VERSION=$(echo $VERSION | cut -d '.' -f2)
PATCH_VERSION=$(echo $VERSION | cut -d '.' -f3)

if [ "$MAJOR_VERSION" -lt 1 ]; then
 echo "Failed to retrieve latest Kerberos release, please download it by yourself"
 return 1
fi

if [ "$MINOR_VERSION" -lt 15 ]; then
 echo "Failed to retrieve latest Kerberos release, please download it by yourself"
 return 1
fi

if [ "$PATCH_VERSION" -lt 0 ]; then
 echo "Failed to retrieve latest Kerberos release, please download it by yourself"
 return 1
fi

if ! [ -d "/opt" ]; then
      echo "The directory $KRB_PREFIX does not exist. Try another one."
      mkdir /opt 
fi

sudo wget http://web.mit.edu/kerberos/dist/krb5/$MAJOR_VERSION.$MINOR_VERSION/krb5-$VERSION.tar.gz -P /opt

if [ $? -ne 0 ]; then 
  echo "Failed to download Kerberos $MAJOR_VERSION.$MINOR_VERSION. Please download it by yourself"
fi

if ! [[ $PATCH_VERSION = "" ]]; then
  echo "patch version non nulle"
  sudo tar xzf /opt/krb5-$MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION.tar.gz -C /opt
  if [ $? -ne 0 ]; then
    echo "Failed to extract Kerberos $MAJOR_VERSION.$MINOR_VERSION files. Please extract them by yourself"
  fi
  cd /opt/krb5-$MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION
  sudo chown -R 1000:1000 /opt/krb5-$MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION
  PWD=$(echo `pwd`)
  echo "ici PWD=$PWD"
  sudo apt-get install bison
  ANSWER=no
  while ! [[ $ANSWER =~ [Y|y] ]] && ! [[ $ANSWER =~ [Y|y]es ]] && ! [[ $ANSWER = "" ]]
  do
    read -p "Please specify prefix directory of your Kerberos installation [/usr/local] : " KRB_PREFIX
    if ! [ -d "$KRB_PREFIX" ]; then
      echo "The directory $KRB_PREFIX does not exist. Try another one."
      continue
    fi
    echo "You entered : $KRB_PREFIX. OK ? [Y/n]"
    read ANSWER
  done
  if ! [[ $KRB_PREFIX = "" ]]; then
    $PWD/src/configure --prefix=$KRB_PREFIX && make && sudo make install
  else 
    # /usr/local by default 
    $PWD/src/configure && make && sudo make install
  fi
else
  echo "patch version nulle"
  sudo tar xzf /opt/krb5-$MAJOR_VERSION.$MINOR_VERSION.tar.gz -C /opt
  if [ $? -ne 0 ]; then
    echo "Failed to extract Kerberos $MAJOR_VERSION.$MINOR_VERSION files. Please extract them by yourself"
  fi
  cd /opt/krb5-$MAJOR_VERSION.$MINOR_VERSION 
  PWD=$(echo `pwd`)
  echo "ici PWD=$PWD"
  sudo apt-get install bison
  ANSWER=no
  while ! [[ $ANSWER =~ [Y|y] ]] && ! [[ $ANSWER =~ [Y|y]es ]] && ! [[ $ANSWER = "" ]]
  do
    read -p "Please specify prefix directory of your Kerberos installation [/usr/local] : " KRB_PREFIX
    if ! [ -d "$KRB_PREFIX" ]; then
      echo "The directory $KRB_PREFIX does not exist. Try another one."
      continue
    fi
    echo "You entered : $KRB_PREFIX. OK ? [Y/n]"
    read ANSWER
  done
  if ! [[ $KRB_PREFIX = "" ]]; then
    $PWD/src/configure --prefix=$KRB_PREFIX && make && sudo make install
  else
    # /usr/local by default 
    $PWD/src/configure && make && sudo make install
  fi
fi

if [ $? -ne 0 ]; then
  echo "Failed to install Kerberos V5 $MAJOR_VERSION.$MINOR_VERSION. Please fix compilation or installation errors before retrying to execute this script."
  return 1
fi

return 0


