#!/bin/bash

ALL_VERSIONS= 
INDEX=1
KRB_PREFIX=
PROXY_USERNAME=
PROXY_PASSWORD=
PROXY_HOST=
PROXY_PORT=
HTTP_PROXY=
HTTPS_PROXY=
START_DIR=$(echo `pwd`)

CURL=$(echo `dpkg -l curl | grep ii | cut -d ' ' -f 1`)
if ! [ $CURL = "ii" ]; then
  sudo apt-get install curl
fi

ALL_VERSIONS=$(echo `curl -s https://api.github.com/repos/krb5/krb5/tags | grep name | grep final | cut -d '"' -f 4 | cut -d "-" -f 2`)

if [[ $ALL_VERSIONS = "" ]]; then
  echo "curl failed to retrieve data. May be behind proxy. Retry."
  if [[ $https_proxy = "" ]]; then
    ANSWER=no
    while ! [[ $ANSWER =~ [Y|y] ]] && ! [[ $ANSWER =~ [Y|y]es ]] && ! [[ $ANSWER = "" ]]
    do
      read -p "Please specify proxy username :" PROXY_USERNAME
      read -s -p "Please specify proxy password :" PROXY_PASSWORD
      read -p "Please specify proxy host :" PROXY_HOST
      read -p "Please specify proxy port :" PROXY_PORT
      HTTPS_PROXY=https://$PROXY_USERNAME:$PROXY_PASSWORD@$PROXY_HOST:$PROXY_PORT
      echo "You chose : https://$PROXY_USERNAME:*********@$PROXY_HOST:$PROXY_PORT. OK ? [Y/n]"
      read ANSWER
    done
  else
    HTTPS_PROXY=$https_proxy
  fi

  ALL_VERSIONS=$(echo `curl -x $HTTPS_PROXY -s https://api.github.com/repos/krb5/krb5/tags | grep name | grep final | cut -d '"' -f 4 | cut -d "-" -f 2`)

  if [[ $ALL_VERSIONS = "" ]]; then
   echo "curl failed to retrieve data. Please download krb5 sources by yourself"
   return 1
  fi
fi

VERSION=$(echo $ALL_VERSIONS |  cut -d " " -f $INDEX)
let "INDEX++"

while ! [[ $VERSION =~ [0-9] ]]
do
  VERSION=$(echo $ALL_VERSIONS |  cut -d " " -f $INDEX)
  let "INDEX++"
done

MAJOR_VERSION=$(echo $VERSION | cut -d '.' -f1)
MINOR_VERSION=$(echo $VERSION | cut -d '.' -f2)
PATCH_VERSION=$(echo $VERSION | cut -d '.' -f3)

if [ "$MAJOR_VERSION" -lt 1 ]; then
 echo "Failed to retrieve latest Kerberos release, please download it by yourself"
 return 1
fi

if [ "$MINOR_VERSION" -lt 15 ]; then
 echo "Failed to retrieve latest Kerberos release, please download it by yourself"
 return 1
fi

if [ "$PATCH_VERSION" -lt 0 ]; then
 echo "Failed to retrieve latest Kerberos release, please download it by yourself"
 return 1
fi

if ! [ -d "/opt" ]; then
  mkdir /opt 
fi

sudo wget --tries=5 http://web.mit.edu/kerberos/dist/krb5/$MAJOR_VERSION.$MINOR_VERSION/krb5-$VERSION.tar.gz -P /opt

if [ $? -ne 0 ]; then
  echo "wget failed to retrieve data. May be behind proxy. Retry."
  if [[ $http_proxy = "" ]]; then
    HTTP_PROXY=http://$PROXY_USERNAME:$PROXY_PASSWORD@$PROXY_HOST:$PROXY_PORT
    echo "HTTP_PROXY=$HTTP_PROXY"
  else
    HTTP_PROXY=$http_proxy
    echo "env var HTTP_PROXY=$HTTP_PROXY"
  fi
  sudo wget -e use_proxy=yes -e http_proxy=$HTTP_PROXY http://web.mit.edu/kerberos/dist/krb5/$MAJOR_VERSION.$MINOR_VERSION/krb5-$VERSION.tar.gz -P /opt
fi

if [ $? -ne 0 ]; then 
  echo "Failed to download Kerberos $MAJOR_VERSION.$MINOR_VERSION. Please download it by yourself"
  return 1
fi

if ! [[ $PATCH_VERSION = "" ]]; then
  sudo tar xzf /opt/krb5-$MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION.tar.gz -C /opt
  if [ $? -ne 0 ]; then
    echo "Failed to extract Kerberos $MAJOR_VERSION.$MINOR_VERSION files. Please extract them by yourself"
    return 1
  fi
  cd /opt/krb5-$MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION
  sudo chown -R 1000:1000 /opt/krb5-$MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION
  PWD=$(echo `pwd`)
  BISON=$(echo `dpkg -l bison | grep ii | cut -d ' ' -f 1`)
  if ! [ $BISON = "ii" ]; then
    sudo apt-get install bison
  fi
  ANSWER=no
  while ! [[ $ANSWER =~ [Y|y] ]] && ! [[ $ANSWER =~ [Y|y]es ]] && ! [[ $ANSWER = "" ]]
  do
    read -p "Please specify prefix directory for your Kerberos installation [/usr/local] : " KRB_PREFIX
    if [[ $KRB_PREFIX = "" ]]; then
      KRB_PREFIX="/usr/local"
    fi
    if ! [ -d "$KRB_PREFIX" ]; then
      echo "The directory $KRB_PREFIX does not exist. Try another one."
      continue
    fi
    echo "You chose : $KRB_PREFIX. OK ? [Y/n]"
    read ANSWER
  done
  $PWD/src/configure --prefix=$KRB_PREFIX && make && sudo make install
else
  sudo tar xzf /opt/krb5-$MAJOR_VERSION.$MINOR_VERSION.tar.gz -C /opt
  if [ $? -ne 0 ]; then
    echo "Failed to extract Kerberos $MAJOR_VERSION.$MINOR_VERSION files. Please extract them by yourself"
    return 1
  fi
  cd /opt/krb5-$MAJOR_VERSION.$MINOR_VERSION 
  PWD=$(echo `pwd`)
  echo PWD=$PWD
  BISON=$(echo `dpkg -l bison | grep ii | cut -d ' ' -f 1`)
  if ! [ $BISON = "ii" ]; then
    sudo apt-get install bison
  fi
  ANSWER=no
  while ! [[ $ANSWER =~ [Y|y] ]] && ! [[ $ANSWER =~ [Y|y]es ]] && ! [[ $ANSWER = "" ]]
  do
    read -p "Please specify prefix directory for your Kerberos installation [/usr/local] : " KRB_PREFIX
    if [[ $KRB_PREFIX = "" ]]; then
      KRB_PREFIX="/usr/local"
    fi
    if ! [ -d "$KRB_PREFIX" ]; then
      echo "The directory $KRB_PREFIX does not exist. Try another one."
      continue
    fi
    echo "You chose : $KRB_PREFIX. OK ? [Y/n]"
    read ANSWER
  done
  $PWD/src/configure --prefix=$KRB_PREFIX && make && sudo make install
fi

if [ $? -ne 0 ]; then
  echo "Failed to install Kerberos V5 $MAJOR_VERSION.$MINOR_VERSION. Please fix compilation or installation errors before retrying to execute this script."
  cd $START_DIR
  return 1
fi

cd $START_DIR
echo
if ! [[ $PATCH_VERSION = "" ]]; then
  echo "Kerberos V5 $MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION have been successfully installed in $KRB_PREFIX"
else
  echo "Kerberos V5 $MAJOR_VERSION.$MINOR_VERSION have been successfully installed in $KRB_PREFIX"
fi

return 0
