#!/bin/bash

KRB5CONFIG=$(which krb5-config)
KRB5PREFIX=$(($KRB5CONFIG --prefix) 2>&1)
KRB5VENDOR=$(($KRB5CONFIG --vendor) 2>&1)
echo "debut: \$1=$1; \$2=$2; \$3=$3"
SUPPLY_USR_HEIMDAL_PATH="false"
  
set_krb_flavour(){
  echo "debut set_krb_flavour: PATH=$PATH"
  if [[ $2 = "" ]]; then
    ANSWER=no
    while ! [[ $ANSWER =~ [Y|y] ]] && ! [[ $ANSWER =~ [Y|y]es ]] && ! [[ $ANSWER = "" ]]
    do
      read -p "l.15: Please specify prefix directory of your $1 installation : " YOURPREFIX
      if ! [ -d "$YOURPREFIX" ]; then
        echo "The directory $YOURPREFIX does not exist. Try another one."
        continue
      fi
      echo "You entered : $YOURPREFIX. OK ? [Y/n]"
      read ANSWER
    done
    SHAVED_PREFIX_DIR=`echo -e "$YOURPREFIX" | sed -e 's/\/$//'`
    NEW_PATH=$SHAVED_PREFIX_DIR/bin:$PATH
    check_path $NEW_PATH
    export PATH=$NEW_PATH
  else
    echo "export PATH directement \$2=$2"
    SHAVED_PREFIX_DIR=`echo -e "$2" | sed -e 's/\/$//'`
    NEW_PATH=$SHAVED_PREFIX_DIR/bin:$PATH
    check_path $NEW_PATH
    export PATH=$NEW_PATH
  fi
}

delete_heimdal_path(){
  ORIGIN_PATH=$PATH
  CURRENT_PATH=$PATH
  #PATH_DELETED=

  echo "on veut MIT: delete heimdal in PATH"

  while true
  do
    HEIMDAL_PATH=`echo ${CURRENT_PATH%%:*}`
    echo "l.138:HEIMDAL_PATH=$HEIMDAL_PATH"
    #if [[ $PATH_DELETED = "" ]]; then
    #  PATH_DELETED=$HEIMDAL_PATH
    #  echo "l.141:PATH_DELETED=$PATH_DELETED"
    #else
    #  PATH_DELETED=$PATH_DELETED:$HEIMDAL_PATH
    #  echo "l.144:PATH_DELETED=$PATH_DELETED"
    #fi
    CURRENT_PATH=`echo ${CURRENT_PATH#*:}`
    if [[ $HEIMDAL_PATH =~ [H|h]eimdal ]] && ! [[ $CURRENT_PATH =~ [H|h]eimdal ]]; then
      break
    fi
  done

  NEW_PATH=`echo ${ORIGIN_PATH/$HEIMDAL_PATH:/}`
  echo "NEW_PATH=$NEW_PATH ; HEIMDAL_PATH=$HEIMDAL_PATH"
}

check_path(){
  ORIGIN_PATH=$1
  CURRENT_PATH=$1
  NEXT_CURRENT_PATH=
  ORIGIN_PATH_LENGTH=${#ORIGIN_PATH}
  PATH_CHECKED_CUT=
  CUT="false"
  echo "on supprime tous les doublons consecutifs; ORIGIN_PATH_LENGTH=$ORIGIN_PATH_LENGTH"

  while true
  do
    if [[ $NEXT_CURRENT_PATH = "" ]]; then
      PATH_TO_CHECK=`echo ${CURRENT_PATH%%:*}`
      echo "l.75:PATH_TO_CHECK=$PATH_TO_CHECK"
      PATH_CHECKED=$PATH_TO_CHECK
    else
      PATH_TO_CHECK=`echo ${NEXT_CURRENT_PATH%%:*}`
      echo "l.78:PATH_TO_CHECK=$PATH_TO_CHECK"
      PATH_CHECKED=$PATH_CHECKED:$PATH_TO_CHECK
      echo "l.81:PATH_CHECKED=$PATH_CHECKED"
    fi
    PATH_TO_CHECK_LENGTH=${#PATH_TO_CHECK}
    PATH_CHECKED_LENGTH=${#PATH_CHECKED}
    echo "PATH_TO_CHECK_LENGTH=$PATH_TO_CHECK_LENGTH; PATH_CHECKED_LENGTH=$PATH_CHECKED_LENGTH"
    NEXT_CURRENT_PATH=`echo ${CURRENT_PATH#*:}`
    echo "NEXT_CURRENT_PATH=$NEXT_CURRENT_PATH"
    NEXT_PATH_TO_CHECK=`echo ${NEXT_CURRENT_PATH%%:*}`
    echo "NEXT_PATH_TO_CHECK=$NEXT_PATH_TO_CHECK"
    if [[ $PATH_TO_CHECK =~ $NEXT_PATH_TO_CHECK ]]; then
      echo "avant delete: CURRENT_PATH=$CURRENT_PATH"
      CURRENT_PATH=`echo ${CURRENT_PATH//$PATH_TO_CHECK:/}`
      #PATH_CHECKED_CUT=$PATH_CHECKED:$CURRENT_PATH
      #CUT="true"
      echo "apres delete: CURRENT_PATH=$CURRENT_PATH; PATH_CHECKED_CUT=$PATH_CHECKED_CUT"
      echo "eq: CURRENT_PATH=$CURRENT_PATH"
      echo "PATH_TO_CHECK=$PATH_TO_CHECK; PATH_TO_CHECK_LENGTH=$PATH_TO_CHECK_LENGTH"
      echo "l.96: PATH_CHECKED_LENGTH=$PATH_CHECKED_LENGTH"
      if [ $PATH_CHECKED_LENGTH = $ORIGIN_PATH_LENGTH ]; then
        echo "break end of line"
        #PATH_CHECKED=`echo ${PATH_CHECKED/:$PATH_TO_CHECK/}`
        #PATH_CHECKED_LENGTH=${#PATH_CHECKED}
        echo "dans le break : CURRENT_PATH=$CURRENT_PATH; KEEP_PATH=$KEEP_PATH"
        break
      fi
    elif [[ $NEXT_CURRENT_PATH = "" ]]; then
      echo "end of PATH : NEXT_CURRENT_PATH=$NEXT_CURRENT_PATH"
      #KEEP_PATH=$PATH_CHECKED:$CURRENT_PATH
      echo "break: KEEP_PATH=$KEEP_PATH; PATH_CHECKED=$PATH_CHECKED; CURRENT_PATH=$CURRENT_PATH"
      #break
    else
      CURRENT_PATH=$NEXT_CURRENT_PATH
    fi
    KEEP_PATH=$PATH_CHECKED:$CURRENT_PATH
    echo "avant le done : CURRENT_PATH=$CURRENT_PATH; KEEP_PATH=$KEEP_PATH; PATH_CHECKED_CUT=$PATH_CHECKED_CUT"
    echo "apres le done : CURRENT_PATH=$CURRENT_PATH; KEEP_PATH=$KEEP_PATH; PATH_CHECKED_CUT=$PATH_CHECKED_CUT"
  done

  NEW_PATH=$KEEP_PATH
  echo "keep : NEW_PATH=$NEW_PATH"
}

if [ "$1" = "Heimdal" ]; then
  if ! [[ $PATH =~ [H|h]eimdal ]]; then
    # Heimdal not set in path(*). Here we are supposed to be in a \case
    # where MIT is installed and running over Heimdal (unless Heimdal is being
    # installed in a non-default directory, so no "heimdal" string presents in PATH).
    # We set it by default to the default installation of Heimdal (/usr/heimdal).
    # If you want an other PATH please specify KRB_INSTALLED_PREFIX.
    # (*) Note in the particular \case where Heimdal is already running,
    # the Heimdal PATH is one of the default existing paths.
    if [[ $2 = "" ]]; then
      echo "l.39: SUPPLY_HEIMDAL_PATH=$SUPPLY_HEIMDAL_PATH"
      if [[ $KRB5VENDOR =~ [H|h]eimdal$ ]] && [ "$FORCE_INSTALL" = "false" ]; then
        echo "l.41: Heimdal is already being set as Kerberos flavour"
        MESSAGE="true"
      elif [ "$SUPPLY_USR_HEIMDAL_PATH" = "false" ]; then
        if ! [ -d "$YOURPREFIX" ]; then
          echo "The directory /usr/heimdal does not exist. Try another one."
          set_krb_flavour Heimdal
        else
          echo "on set /usr/heimdal/bin"
          export PATH=/usr/heimdal/bin:$PATH
          SUPPLY_USR_HEIMDAL_PATH="true"
        fi
      else
        echo "call set flavour function"
        set_krb_flavour Heimdal
      fi
    else
      if [[ $KRB5VENDOR =~ [H|h]eimdal$ ]] && [ "$FORCE_INSTALL" = "false" ]; then
        echo "l.54: Heimdal is already being set as Kerberos flavour"
        MESSAGE="true"
      else
        if ! [ -d "$2" ]; then
          echo "The directory $2 does not exist. Try another one."
          set_krb_flavour Heimdal
        else
          SHAVED_PREFIX_DIR=`echo -e "$2" | sed -e 's/\/$//'`
	  echo "on set $2 pour heimdal"
          NEW_PATH=$SHAVED_PREFIX_DIR/bin:$PATH
          check_path $NEW_PATH
          export PATH=$NEW_PATH
        fi
      fi
    fi
  else
	echo  "l.62: delete heimdal in path"
    # delete Heimdal in PATH and export PATH with Heimdal
    # to ensure Heimdal is first Kerberos in PATH
    delete_heimdal_path    
    echo "NEW_PATH=$NEW_PATH; \$2=$2"  

    if ! [[ $2 = "" ]]; then
      echo "le deuxieme argument nest pas nul"
      if ! [ -d "$2" ]; then
        echo "The directory $2 does not exist. Try another one."
        set_krb_flavour Heimdal
      else
        SHAVED_PREFIX_DIR=`echo -e "$2" | sed -e 's/\/$//'`
        NEW_PATH=$SHAVED_PREFIX_DIR/bin:$NEW_PATH
        check_path $NEW_PATH
        export PATH=$NEW_PATH
      fi
    else
      if [[ $KRB5VENDOR =~ [H|h]eimdal$ ]] && [ "$FORCE_INSTALL" = "false" ]; then
        echo "l.93: Heimdal is already being set as Kerberos flavour"
        MESSAGE="true"
        NEW_PATH=$KRB5PREFIX/bin:$NEW_PATH
        check_path $NEW_PATH
        export PATH=$NEW_PATH
      else
        ANSWER=no
        while ! [[ $ANSWER =~ [Y|y] ]] && ! [[ $ANSWER =~ [Y|y]es ]] && ! [[ $ANSWER = "" ]]
        do
          read -p "l.100: Please specify prefix directory of your Heimdal installation : " YOURPREFIX
          if ! [ -d "$YOURPREFIX" ]; then
            echo "The directory $YOURPREFIX does not exist. Try another one."
            continue
          fi
          echo "You entered : $YOURPREFIX. OK ? [Y/n]"
          read ANSWER
        done
        SHAVED_PREFIX_DIR=`echo -e "$YOURPREFIX" | sed -e 's/\/$//'`
        NEW_PATH=$SHAVED_PREFIX_DIR/bin:$NEW_PATH
        check_path $NEW_PATH
        export PATH=$NEW_PATH
      fi
    fi
  fi
else
  echo "on veut du MIT: \$1=$1; \$2=$2; \$3=$3"
  if [[ $KRB5CONFIG =~ [H|h]eimdal ]]; then
    # delete Heimdal in PATH
    delete_heimdal_path    
    echo "MIT wish : NEW_PATH=$NEW_PATH; \$3=$3" 
    echo "l.136: PATH=$PATH; FORCE_INSTALL=$FORCE_INSTALL"
    if [[ $FORCE_INSTALL = "true" ]]; then
      echo "MIT Kerberos : force new install: \$3=$3"
      set_krb_flavour MIT $3
    else
      check_path $NEW_PATH
      export PATH=$NEW_PATH
    fi
  else
     if [[ $KRB5VENDOR =~ [H|h]eimdal$ ]]; then
	echo "MIT wanted; Heimdal vendor; on set \$2=$2 ; \$3=$3"
	set_krb_flavour MIT $3
     else
       if [ "$FORCE_INSTALL" = "false" ]; then
         echo "l.100: MIT is already being set as Kerberos flavour"
	 if [[ $PATH =~ [H|h]eimdal ]]; then
           #delete Heimdal in PATH if present
           delete_heimdal_path
           export PATH=$NEW_PATH
         fi
         MESSAGE="true"
       else
	 if [ "$CHECK_VERSION" = "false" ]; then
           echo "Force new install MIT Kerberos : \$3=$3"
           set_krb_flavour MIT $3
         else
           echo "MIT Kerberos already installed"
           MESSAGE="true"
         fi
       fi
     fi
  fi
fi
